name: Deploy with SSH Password

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Rsync files to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz \
            --exclude 'aura-news-backend/storage/' \
            --exclude 'aura-news-backend/.env' \
            --exclude 'aura-news-frontend/dist/' \
            -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/var/www/aura-news

      - name: Generate sitemap on server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'cd /var/www/aura-news/aura-news-frontend && node generate-sitemap.cjs'

      - name: Run deploy script
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} 'cd /var/www/aura-news && ./deploy.sh' 
